name: Run Examples

on:
    pull_request:
        types: [labeled]

jobs:
    run-examples:
        if: github.event.label.name == 'Run examples'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Echo Hello World
              run: echo "Hello World"

            - name: Remove label
              uses: actions/github-script@v7
              with:
                  script: |
                      await github.rest.issues.removeLabel({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        name: 'Run examples'
                      });
